name: Example Workflow

on:
  push:
    branches:
      - master  # Adjust the branch name as needed
  workflow_dispatch:
  
jobs:
  display-variables:
    name: test
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Use variables
      run: |
        echo "repository variable : $FUNCTION_NAME"
      env:
        FUNCTION_NAME: ${{ vars.FUNCTION_NAME }}
