name: Example Workflow

on:
  push:
    branches:
      - master  # Adjust the branch name as needed
  workflow_dispatch:
  
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch environment variable
        run: echo "My secret variable is $FUNCTION_NAME"
        env:
          FUNCTION_NAME: ${{ env.FUNCTION_NAME }}
